name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PUBLISH_PATH: '.'
  AZURE_WEB_APP: 'TestWebAppspn'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish 
      run: dotnet publish --configuration Release -o '${{env.PUBLISH_PATH}}/publish'
     
    - name: Azure WebApp Deploy 
      uses: Azure/webapps-deploy@v2
      with:
       # Name of the Azure Web App
       app-name: '${{env.AZURE_WEB_APP}}'         
       publish-profile: '${{secrets.SECRETWEBAPP}}'
       package: '${{env.PUBLISH_PATH}}/publish'
          
    
